import { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import React from "react";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
  params: {
    country: string;
  };
};

export default function Layout({ children, params }: LayoutProps) {
  return (
    <main className="flex h-screen md:grid md:grid-cols-[20rem_auto] lg:gap-10">
      <Sidebar params={params} />
      <section className="p-[40px_30px_40px_40px]">
        <div>
          <Link href={`/${params.country}`}>Click to Go Home</Link>
        </div>
        <div>{children}</div>
      </section>
    </main>
  );
}
