import { RightSidebarNavigation } from "@/components/right-sidebar-navigation";
import { Sidebar } from "@/components/sidebar";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type LayoutProps = {
  children: React.ReactNode;
  params: {
    country: string;
  };
};

export default function Layout({ children, params }: LayoutProps) {
  return (
    <main className="flex flex-col">
      <header className="h-20 w-full"></header>
      <div className=" max-w-8xl relative mx-auto flex w-full flex-auto justify-center sm:px-2 lg:px-8 xl:px-20">
        <Sidebar />
        <div className="min-w-0 max-w-4xl flex-auto px-4 py-16 lg:pl-8 lg:pr-0 xl:px-16">
          {children}
        </div>
        <RightSidebarNavigation />
      </div>
    </main>
  );
}
